options:
  partition-name:
    type: string
    default:
    description: >
      Name by which the partition may be referenced (e.g. `Interactive`).

      Note: the partition name should only contain letters, numbers, and
      hyphens. Spaces are not allowed.
  partition-config:
    type: string
    default: ""
    description: >
      Extra partition configuration specified as a space separated `key=value`
      single line.
  partition-state:
    type: string
    default: "UP"
    description: >
      State of partition or availability for use. Possible values are `UP`,
      `DOWN`, `DRAIN` and `INACTIVE`. The default value is `UP`. See also the
      related `Alternate` keyword.
  nhc-conf:
    default: ""
    type: string
    description: >
      Custom extra configuration to use for Node Health Check.

      These lines are appended to a basic `nhc.conf` provided by the charm.
