name: LintAndBuild

on: pull_request

jobs:
  lint-charms:
    name: "Lint the charms"
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          architecture: 'x64'
      - name: "Install tox"
        run: |
          pip install tox
      - name: "lint the charms"
        run: |
          make lint

  build-charms:
    name: "Build the charms"
    needs: lint-charms
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: "Install charmcraft"
        run: |
          sudo snap install charmcraft --channel=latest/stable --classic
      - name: "Install lxd"
        run: |
          sudo snap install lxd --channel=latest/stable
          sudo snap refresh lxd
      - name: "Configure lxd"
        run: |
          sudo groupadd --force --system lxd
          sudo usermod --append --groups lxd $USER
          newgrp lxd
          sudo snap start lxd
          sudo lxd waitready --timeout=30
          sudo lxd init --auto
      - name: "Build the charms"
        shell: bash
        run: |
          make version
          echo "charm version: $(cat version)"

          for charm in slurmd slurmctld slurmdbd slurmrestd; do
              sg lxd -c "charmcraft -v pack --project-dir charm-$charm"
              cp ${charm}_ubuntu-20.04-amd64_centos-7-amd64.charm ${charm}.charm
          done

          file *.charm
